version: '3'
services:
  xianyu-agent:
    container_name: xianyu-agent
    image: xianyu-agent:latest
    restart: always
    volumes:
      - ./.env:/app/.env
      # - ./pompts:/app/pompts # 自定义提示词需按照prompts文件名定义

